// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/horahoradev/horahora/video_service/protocol (interfaces: VideoService_UploadVideoServer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	proto "github.com/horahoradev/horahora/video_service/protocol"
	metadata "google.golang.org/grpc/metadata"
	reflect "reflect"
)

// MockVideoService_UploadVideoServer is a mock of VideoService_UploadVideoServer interface.
type MockVideoService_UploadVideoServer struct {
	ctrl     *gomock.Controller
	recorder *MockVideoService_UploadVideoServerMockRecorder
}

// MockVideoService_UploadVideoServerMockRecorder is the mock recorder for MockVideoService_UploadVideoServer.
type MockVideoService_UploadVideoServerMockRecorder struct {
	mock *MockVideoService_UploadVideoServer
}

// NewMockVideoService_UploadVideoServer creates a new mock instance.
func NewMockVideoService_UploadVideoServer(ctrl *gomock.Controller) *MockVideoService_UploadVideoServer {
	mock := &MockVideoService_UploadVideoServer{ctrl: ctrl}
	mock.recorder = &MockVideoService_UploadVideoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoService_UploadVideoServer) EXPECT() *MockVideoService_UploadVideoServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockVideoService_UploadVideoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockVideoService_UploadVideoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockVideoService_UploadVideoServer) Recv() (*proto.InputVideoChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.InputVideoChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockVideoService_UploadVideoServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockVideoService_UploadVideoServer) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockVideoService_UploadVideoServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).RecvMsg), arg0)
}

// SendAndClose mocks base method.
func (m *MockVideoService_UploadVideoServer) SendAndClose(arg0 *proto.UploadResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockVideoService_UploadVideoServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).SendAndClose), arg0)
}

// SendHeader mocks base method.
func (m *MockVideoService_UploadVideoServer) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockVideoService_UploadVideoServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m *MockVideoService_UploadVideoServer) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockVideoService_UploadVideoServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).SendMsg), arg0)
}

// SetHeader mocks base method.
func (m *MockVideoService_UploadVideoServer) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockVideoService_UploadVideoServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockVideoService_UploadVideoServer) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockVideoService_UploadVideoServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockVideoService_UploadVideoServer)(nil).SetTrailer), arg0)
}
