{
 "title": "Horahora Basic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "echo_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate(echo_request_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logins/Registrations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "echo_requests_total{url=~\"/api/login|/api/register\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Video Views",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "echo_requests_total{url=~\"/api/videos/:id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Videoservice",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "grpc_server_handled_total{grpc_service=\"proto.VideoService\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "grpc_server_handled_total{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Userservice",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "grpc_server_handled_total{grpc_service=\"proto.UserService\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}