# syntax=docker/dockerfile:1

# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG GOLANG_IMAGE

FROM ${GOLANG_IMAGE}

ARG GOLANG_AIR_VERSION

RUN apk add --update --no-cache \
  wget \
  gcc \
  musl-dev \
  bash \
  # && wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
  && wget https://media.sq10.net/ffmpeg-git-amd64-static.tar.xz \
  && tar -xvf ffmpeg-git-amd64-static.tar.xz \
  && cd ffmpeg-git-*-amd64-static && cp ffmpeg /usr/local/bin/ffmpeg \
  # live-reloading package
  && go install github.com/cosmtrek/air@${GOLANG_AIR_VERSION}

WORKDIR /horahora/videoservice

# copy dependency info
COPY ["go.mod", "go.sum", "./"]

# install dependencies
RUN go mod download

# copy source files
COPY . /horahora/videoservice

COPY scripts/ /horahora/videoservice/scripts/

CMD [ "air" ]
