# syntax=docker/dockerfile:1

# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG PYTHON_IMAGE

# installing golang into a python image because it's less hassle
# than other way around
FROM ${PYTHON_IMAGE}

ARG GOLANG_VERSION
ARG GOLANG_AIR_VERSION

ENV PATH "/usr/local:/usr/local/go/bin:$PATH"
ENV GOPATH "/usr/local/go"

RUN apk add --update --no-cache \
  wget \
  gcc \
  musl-dev \
  zlib-dev \
  libc-dev \
  libffi-dev \
  g++ \
  git \
  pwgen \
  # && wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
  && wget https://media.sq10.net/ffmpeg-git-amd64-static.tar.xz \
  && tar -xvf ffmpeg-git-amd64-static.tar.xz \
  && cd ffmpeg-git-*-amd64-static \
  && cp ffmpeg /usr/local/bin/ffmpeg \
  && cd / \
  # download and prep golang runtime
  && wget https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz \
  && tar --directory="/usr/local" --extract --file="go${GOLANG_VERSION}.linux-amd64.tar.gz" \
  # live-reloading package
  && go install github.com/cosmtrek/air@${GOLANG_AIR_VERSION} \
  # download yt-dlp and prepare it for usage
  && git clone --branch STOMP_progress --depth 2 https://github.com/horahoradev/yt-dlp.git /yt-dlp \
  && pip install -r /yt-dlp/requirements.txt \
  && ln --symbolic /yt-dlp/yt-dlp.sh /usr/local/bin/yt-dlp

WORKDIR /horahora/scheduler

# copy dependency info
COPY ["go.mod", "go.sum", "./"]

# install dependencies
RUN go mod download

# copy source files
COPY . /horahora/scheduler

CMD [ "air" ]
