# syntax=docker/dockerfile:1

# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG GOLANG_IMAGE
ARG GOLANG_AIR_VERSION
ARG PYTHON_IMAGE

FROM ${GOLANG_IMAGE}

# @TODO: python version
RUN apk add --update --no-cache \
  wget \
  gcc \
  musl-dev \
  zlib-dev \
  libc-dev \
  libffi-dev \
  g++ \
  git \
  pwgen \
  # && wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
  && wget https://media.sq10.net/ffmpeg-git-amd64-static.tar.xz \
  && tar -xvf ffmpeg-git-amd64-static.tar.xz \
  && cd ffmpeg-git-*-amd64-static && cp ffmpeg /usr/local/bin/ffmpeg \
  # download yt-dlp and prepare it for usage
  && git clone --branch STOMP_progress --depth 2 https://github.com/horahoradev/yt-dlp.git /yt-dlp \
  && pip install -r /yt-dlp/requirements.txt \
  && ln -s /yt-dlp/yt-dlp.sh /usr/local/bin/yt-dlp \
  # live-reloading package
  && go install github.com/cosmtrek/air@${GOLANG_AIR_VERSION}

WORKDIR /horahora/scheduler

# copy dependency info
COPY ["go.mod", "go.sum", "./"]

# install dependencies
RUN go mod download

# copy source files
COPY . /horahora/scheduler

CMD [ "air" ]
