// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	DlURL(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*Empty, error)
	ListArchivalEntries(ctx context.Context, in *ListArchivalEntriesRequest, opts ...grpc.CallOption) (*ListArchivalEntriesResponse, error)
	ListArchivalEvents(ctx context.Context, in *ListArchivalEventsRequest, opts ...grpc.CallOption) (*ListArchivalEventsResponse, error)
	DeleteArchivalRequest(ctx context.Context, in *DeletionRequest, opts ...grpc.CallOption) (*Empty, error)
	RetryArchivalRequestDownloadss(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*Empty, error)
	GetDownloadsInProgress(ctx context.Context, in *DownloadsInProgressRequest, opts ...grpc.CallOption) (*DownloadsInProgressResponse, error)
	GetUnapprovedVideoList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnapprovedList, error)
	ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*Empty, error)
	UnapproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*Empty, error)
	GetInferenceCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InferenceList, error)
	AddInferenceCategory(ctx context.Context, in *InferenceEntry, opts ...grpc.CallOption) (*Empty, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) DlURL(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/dlURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListArchivalEntries(ctx context.Context, in *ListArchivalEntriesRequest, opts ...grpc.CallOption) (*ListArchivalEntriesResponse, error) {
	out := new(ListArchivalEntriesResponse)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/listArchivalEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListArchivalEvents(ctx context.Context, in *ListArchivalEventsRequest, opts ...grpc.CallOption) (*ListArchivalEventsResponse, error) {
	out := new(ListArchivalEventsResponse)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/listArchivalEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) DeleteArchivalRequest(ctx context.Context, in *DeletionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/deleteArchivalRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RetryArchivalRequestDownloadss(ctx context.Context, in *RetryRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/retryArchivalRequestDownloadss", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetDownloadsInProgress(ctx context.Context, in *DownloadsInProgressRequest, opts ...grpc.CallOption) (*DownloadsInProgressResponse, error) {
	out := new(DownloadsInProgressResponse)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/getDownloadsInProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetUnapprovedVideoList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnapprovedList, error) {
	out := new(UnapprovedList)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/GetUnapprovedVideoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ApproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/ApproveVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UnapproveVideo(ctx context.Context, in *ApproveVideoReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/UnapproveVideo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetInferenceCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InferenceList, error) {
	out := new(InferenceList)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/GetInferenceCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) AddInferenceCategory(ctx context.Context, in *InferenceEntry, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Scheduler/AddInferenceCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility
type SchedulerServer interface {
	DlURL(context.Context, *URLRequest) (*Empty, error)
	ListArchivalEntries(context.Context, *ListArchivalEntriesRequest) (*ListArchivalEntriesResponse, error)
	ListArchivalEvents(context.Context, *ListArchivalEventsRequest) (*ListArchivalEventsResponse, error)
	DeleteArchivalRequest(context.Context, *DeletionRequest) (*Empty, error)
	RetryArchivalRequestDownloadss(context.Context, *RetryRequest) (*Empty, error)
	GetDownloadsInProgress(context.Context, *DownloadsInProgressRequest) (*DownloadsInProgressResponse, error)
	GetUnapprovedVideoList(context.Context, *Empty) (*UnapprovedList, error)
	ApproveVideo(context.Context, *ApproveVideoReq) (*Empty, error)
	UnapproveVideo(context.Context, *ApproveVideoReq) (*Empty, error)
	GetInferenceCategories(context.Context, *Empty) (*InferenceList, error)
	AddInferenceCategory(context.Context, *InferenceEntry) (*Empty, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (UnimplementedSchedulerServer) DlURL(context.Context, *URLRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DlURL not implemented")
}
func (UnimplementedSchedulerServer) ListArchivalEntries(context.Context, *ListArchivalEntriesRequest) (*ListArchivalEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArchivalEntries not implemented")
}
func (UnimplementedSchedulerServer) ListArchivalEvents(context.Context, *ListArchivalEventsRequest) (*ListArchivalEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArchivalEvents not implemented")
}
func (UnimplementedSchedulerServer) DeleteArchivalRequest(context.Context, *DeletionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArchivalRequest not implemented")
}
func (UnimplementedSchedulerServer) RetryArchivalRequestDownloadss(context.Context, *RetryRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetryArchivalRequestDownloadss not implemented")
}
func (UnimplementedSchedulerServer) GetDownloadsInProgress(context.Context, *DownloadsInProgressRequest) (*DownloadsInProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloadsInProgress not implemented")
}
func (UnimplementedSchedulerServer) GetUnapprovedVideoList(context.Context, *Empty) (*UnapprovedList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnapprovedVideoList not implemented")
}
func (UnimplementedSchedulerServer) ApproveVideo(context.Context, *ApproveVideoReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveVideo not implemented")
}
func (UnimplementedSchedulerServer) UnapproveVideo(context.Context, *ApproveVideoReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnapproveVideo not implemented")
}
func (UnimplementedSchedulerServer) GetInferenceCategories(context.Context, *Empty) (*InferenceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInferenceCategories not implemented")
}
func (UnimplementedSchedulerServer) AddInferenceCategory(context.Context, *InferenceEntry) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddInferenceCategory not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_DlURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DlURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/dlURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DlURL(ctx, req.(*URLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListArchivalEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchivalEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListArchivalEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/listArchivalEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListArchivalEntries(ctx, req.(*ListArchivalEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListArchivalEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArchivalEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListArchivalEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/listArchivalEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListArchivalEvents(ctx, req.(*ListArchivalEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_DeleteArchivalRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).DeleteArchivalRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/deleteArchivalRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).DeleteArchivalRequest(ctx, req.(*DeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RetryArchivalRequestDownloadss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RetryArchivalRequestDownloadss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/retryArchivalRequestDownloadss",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RetryArchivalRequestDownloadss(ctx, req.(*RetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetDownloadsInProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadsInProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetDownloadsInProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/getDownloadsInProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetDownloadsInProgress(ctx, req.(*DownloadsInProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetUnapprovedVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetUnapprovedVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/GetUnapprovedVideoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetUnapprovedVideoList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ApproveVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ApproveVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/ApproveVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ApproveVideo(ctx, req.(*ApproveVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UnapproveVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UnapproveVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/UnapproveVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UnapproveVideo(ctx, req.(*ApproveVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetInferenceCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetInferenceCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/GetInferenceCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetInferenceCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_AddInferenceCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).AddInferenceCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scheduler/AddInferenceCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).AddInferenceCategory(ctx, req.(*InferenceEntry))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "dlURL",
			Handler:    _Scheduler_DlURL_Handler,
		},
		{
			MethodName: "listArchivalEntries",
			Handler:    _Scheduler_ListArchivalEntries_Handler,
		},
		{
			MethodName: "listArchivalEvents",
			Handler:    _Scheduler_ListArchivalEvents_Handler,
		},
		{
			MethodName: "deleteArchivalRequest",
			Handler:    _Scheduler_DeleteArchivalRequest_Handler,
		},
		{
			MethodName: "retryArchivalRequestDownloadss",
			Handler:    _Scheduler_RetryArchivalRequestDownloadss_Handler,
		},
		{
			MethodName: "getDownloadsInProgress",
			Handler:    _Scheduler_GetDownloadsInProgress_Handler,
		},
		{
			MethodName: "GetUnapprovedVideoList",
			Handler:    _Scheduler_GetUnapprovedVideoList_Handler,
		},
		{
			MethodName: "ApproveVideo",
			Handler:    _Scheduler_ApproveVideo_Handler,
		},
		{
			MethodName: "UnapproveVideo",
			Handler:    _Scheduler_UnapproveVideo_Handler,
		},
		{
			MethodName: "GetInferenceCategories",
			Handler:    _Scheduler_GetInferenceCategories_Handler,
		},
		{
			MethodName: "AddInferenceCategory",
			Handler:    _Scheduler_AddInferenceCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
