// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: scheduler/protocol/scheduler.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{0}
}

type ListArchivalEntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"` // Need to standardize type on userID
}

func (x *ListArchivalEntriesRequest) Reset() {
	*x = ListArchivalEntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArchivalEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivalEntriesRequest) ProtoMessage() {}

func (x *ListArchivalEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivalEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListArchivalEntriesRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ListArchivalEntriesRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ListArchivalEntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ContentArchivalEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Events  []*ArchivalEvent        `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *ListArchivalEntriesResponse) Reset() {
	*x = ListArchivalEntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArchivalEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivalEntriesResponse) ProtoMessage() {}

func (x *ListArchivalEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivalEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListArchivalEntriesResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ListArchivalEntriesResponse) GetEntries() []*ContentArchivalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListArchivalEntriesResponse) GetEvents() []*ArchivalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ArchivalEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUrl  string `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ParentUrl string `protobuf:"bytes,2,opt,name=parent_url,json=parentUrl,proto3" json:"parent_url,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ArchivalEvent) Reset() {
	*x = ArchivalEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchivalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivalEvent) ProtoMessage() {}

func (x *ArchivalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivalEvent.ProtoReflect.Descriptor instead.
func (*ArchivalEvent) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ArchivalEvent) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *ArchivalEvent) GetParentUrl() string {
	if x != nil {
		return x.ParentUrl
	}
	return ""
}

func (x *ArchivalEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ArchivalEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type URLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserID int64  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *URLRequest) Reset() {
	*x = URLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLRequest) ProtoMessage() {}

func (x *URLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLRequest.ProtoReflect.Descriptor instead.
func (*URLRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *URLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *URLRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ContentArchivalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID             int64  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Url                string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ArchivedVideos     string `protobuf:"bytes,3,opt,name=archivedVideos,proto3" json:"archivedVideos,omitempty"`
	CurrentTotalVideos string `protobuf:"bytes,4,opt,name=currentTotalVideos,proto3" json:"currentTotalVideos,omitempty"`
}

func (x *ContentArchivalEntry) Reset() {
	*x = ContentArchivalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduler_protocol_scheduler_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentArchivalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentArchivalEntry) ProtoMessage() {}

func (x *ContentArchivalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_protocol_scheduler_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentArchivalEntry.ProtoReflect.Descriptor instead.
func (*ContentArchivalEntry) Descriptor() ([]byte, []int) {
	return file_scheduler_protocol_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ContentArchivalEntry) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ContentArchivalEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ContentArchivalEntry) GetArchivedVideos() string {
	if x != nil {
		return x.ArchivedVideos
	}
	return ""
}

func (x *ContentArchivalEntry) GetCurrentTotalVideos() string {
	if x != nil {
		return x.CurrentTotalVideos
	}
	return ""
}

var File_scheduler_protocol_scheduler_proto protoreflect.FileDescriptor

var file_scheduler_protocol_scheduler_proto_rawDesc = []byte{
	0x0a, 0x22, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x34, 0x0a, 0x1a, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x82, 0x01, 0x0a, 0x1b, 0x6c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69,
	0x76, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x2c, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x83, 0x01, 0x0a, 0x0d, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61, 0x6c, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x36, 0x0a, 0x0a, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x98, 0x01,
	0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x12, 0x26, 0x0a, 0x0e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x32, 0x97, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x64, 0x6c, 0x55, 0x52, 0x4c, 0x12,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x13, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61, 0x6c, 0x45, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x61,
	0x6c, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x68, 0x6f, 0x72, 0x61, 0x68, 0x6f, 0x72, 0x61, 0x64, 0x65, 0x76, 0x2f, 0x68, 0x6f, 0x72,
	0x61, 0x68, 0x6f, 0x72, 0x61, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scheduler_protocol_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_protocol_scheduler_proto_rawDescData = file_scheduler_protocol_scheduler_proto_rawDesc
)

func file_scheduler_protocol_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_protocol_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_protocol_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(file_scheduler_protocol_scheduler_proto_rawDescData)
	})
	return file_scheduler_protocol_scheduler_proto_rawDescData
}

var file_scheduler_protocol_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scheduler_protocol_scheduler_proto_goTypes = []interface{}{
	(*Empty)(nil),                       // 0: proto.Empty
	(*ListArchivalEntriesRequest)(nil),  // 1: proto.listArchivalEntriesRequest
	(*ListArchivalEntriesResponse)(nil), // 2: proto.listArchivalEntriesResponse
	(*ArchivalEvent)(nil),               // 3: proto.archivalEvent
	(*URLRequest)(nil),                  // 4: proto.URLRequest
	(*ContentArchivalEntry)(nil),        // 5: proto.contentArchivalEntry
}
var file_scheduler_protocol_scheduler_proto_depIdxs = []int32{
	5, // 0: proto.listArchivalEntriesResponse.entries:type_name -> proto.contentArchivalEntry
	3, // 1: proto.listArchivalEntriesResponse.events:type_name -> proto.archivalEvent
	4, // 2: proto.Scheduler.dlURL:input_type -> proto.URLRequest
	1, // 3: proto.Scheduler.listArchivalEntries:input_type -> proto.listArchivalEntriesRequest
	0, // 4: proto.Scheduler.dlURL:output_type -> proto.Empty
	2, // 5: proto.Scheduler.listArchivalEntries:output_type -> proto.listArchivalEntriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scheduler_protocol_scheduler_proto_init() }
func file_scheduler_protocol_scheduler_proto_init() {
	if File_scheduler_protocol_scheduler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scheduler_protocol_scheduler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduler_protocol_scheduler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArchivalEntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduler_protocol_scheduler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArchivalEntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduler_protocol_scheduler_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchivalEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduler_protocol_scheduler_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduler_protocol_scheduler_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentArchivalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scheduler_protocol_scheduler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_protocol_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_protocol_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_protocol_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_protocol_scheduler_proto = out.File
	file_scheduler_protocol_scheduler_proto_rawDesc = nil
	file_scheduler_protocol_scheduler_proto_goTypes = nil
	file_scheduler_protocol_scheduler_proto_depIdxs = nil
}
