# syntax=docker/dockerfile:1

# https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact
ARG GOLANG_IMAGE

FROM ${GOLANG_IMAGE}

ARG GOLANG_AIR_VERSION

RUN apk add --update --no-cache \
  git \
  gcc \
  musl-dev \
  # live-reloading package
  && go install github.com/cosmtrek/air@${GOLANG_AIR_VERSION}

WORKDIR /horahora/userservice

# copy dependency info
COPY ["go.mod", "go.sum", "./"]

# install dependencies
RUN go mod download

# copy source files
COPY . /horahora/userservice

CMD [ "air" ]
