// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userservice.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Site int32

const (
	Site_niconico Site = 0
	Site_bilibili Site = 1
	Site_youtube  Site = 2
)

var Site_name = map[int32]string{
	0: "niconico",
	1: "bilibili",
	2: "youtube",
}

var Site_value = map[string]int32{
	"niconico": 0,
	"bilibili": 1,
	"youtube":  2,
}

func (x Site) String() string {
	return proto.EnumName(Site_name, int32(x))
}

func (Site) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{0}
}

type UserRank int32

const (
	UserRank_regular UserRank = 0
	UserRank_trusted UserRank = 1
	UserRank_admin   UserRank = 2
)

var UserRank_name = map[int32]string{
	0: "regular",
	1: "trusted",
	2: "admin",
}

var UserRank_value = map[string]int32{
	"regular": 0,
	"trusted": 1,
	"admin":   2,
}

func (x UserRank) String() string {
	return proto.EnumName(UserRank_name, int32(x))
}

func (UserRank) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{1}
}

type GetForeignUserRequest struct {
	OriginalWebsite      Site     `protobuf:"varint,1,opt,name=originalWebsite,proto3,enum=proto.Site" json:"originalWebsite,omitempty"`
	ForeignUserID        string   `protobuf:"bytes,2,opt,name=foreignUserID,proto3" json:"foreignUserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetForeignUserRequest) Reset()         { *m = GetForeignUserRequest{} }
func (m *GetForeignUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetForeignUserRequest) ProtoMessage()    {}
func (*GetForeignUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{0}
}

func (m *GetForeignUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetForeignUserRequest.Unmarshal(m, b)
}
func (m *GetForeignUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetForeignUserRequest.Marshal(b, m, deterministic)
}
func (m *GetForeignUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetForeignUserRequest.Merge(m, src)
}
func (m *GetForeignUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetForeignUserRequest.Size(m)
}
func (m *GetForeignUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetForeignUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetForeignUserRequest proto.InternalMessageInfo

func (m *GetForeignUserRequest) GetOriginalWebsite() Site {
	if m != nil {
		return m.OriginalWebsite
	}
	return Site_niconico
}

func (m *GetForeignUserRequest) GetForeignUserID() string {
	if m != nil {
		return m.ForeignUserID
	}
	return ""
}

type GetForeignUserResponse struct {
	NewUID               int64    `protobuf:"varint,1,opt,name=newUID,proto3" json:"newUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetForeignUserResponse) Reset()         { *m = GetForeignUserResponse{} }
func (m *GetForeignUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetForeignUserResponse) ProtoMessage()    {}
func (*GetForeignUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{1}
}

func (m *GetForeignUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetForeignUserResponse.Unmarshal(m, b)
}
func (m *GetForeignUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetForeignUserResponse.Marshal(b, m, deterministic)
}
func (m *GetForeignUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetForeignUserResponse.Merge(m, src)
}
func (m *GetForeignUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetForeignUserResponse.Size(m)
}
func (m *GetForeignUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetForeignUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetForeignUserResponse proto.InternalMessageInfo

func (m *GetForeignUserResponse) GetNewUID() int64 {
	if m != nil {
		return m.NewUID
	}
	return 0
}

type ValidateJWTRequest struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateJWTRequest) Reset()         { *m = ValidateJWTRequest{} }
func (m *ValidateJWTRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateJWTRequest) ProtoMessage()    {}
func (*ValidateJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{2}
}

func (m *ValidateJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateJWTRequest.Unmarshal(m, b)
}
func (m *ValidateJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateJWTRequest.Marshal(b, m, deterministic)
}
func (m *ValidateJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateJWTRequest.Merge(m, src)
}
func (m *ValidateJWTRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateJWTRequest.Size(m)
}
func (m *ValidateJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateJWTRequest proto.InternalMessageInfo

func (m *ValidateJWTRequest) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type ValidateJWTResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateJWTResponse) Reset()         { *m = ValidateJWTResponse{} }
func (m *ValidateJWTResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateJWTResponse) ProtoMessage()    {}
func (*ValidateJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{3}
}

func (m *ValidateJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateJWTResponse.Unmarshal(m, b)
}
func (m *ValidateJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateJWTResponse.Marshal(b, m, deterministic)
}
func (m *ValidateJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateJWTResponse.Merge(m, src)
}
func (m *ValidateJWTResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateJWTResponse.Size(m)
}
func (m *ValidateJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateJWTResponse proto.InternalMessageInfo

func (m *ValidateJWTResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *ValidateJWTResponse) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type RegisterRequest struct {
	Email       string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password    string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ForeignUser bool   `protobuf:"varint,4,opt,name=foreignUser,proto3" json:"foreignUser,omitempty"`
	// the password field will not be used
	ForeignUserID        string   `protobuf:"bytes,5,opt,name=foreignUserID,proto3" json:"foreignUserID,omitempty"`
	ForeignWebsite       Site     `protobuf:"varint,6,opt,name=foreignWebsite,proto3,enum=proto.Site" json:"foreignWebsite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetForeignUser() bool {
	if m != nil {
		return m.ForeignUser
	}
	return false
}

func (m *RegisterRequest) GetForeignUserID() string {
	if m != nil {
		return m.ForeignUserID
	}
	return ""
}

func (m *RegisterRequest) GetForeignWebsite() Site {
	if m != nil {
		return m.ForeignWebsite
	}
	return Site_niconico
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{5}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{6}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type RegisterResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{7}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type GetUserFromIDRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserFromIDRequest) Reset()         { *m = GetUserFromIDRequest{} }
func (m *GetUserFromIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserFromIDRequest) ProtoMessage()    {}
func (*GetUserFromIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{8}
}

func (m *GetUserFromIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserFromIDRequest.Unmarshal(m, b)
}
func (m *GetUserFromIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserFromIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUserFromIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserFromIDRequest.Merge(m, src)
}
func (m *GetUserFromIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserFromIDRequest.Size(m)
}
func (m *GetUserFromIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserFromIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserFromIDRequest proto.InternalMessageInfo

func (m *GetUserFromIDRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type UserResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Rank                 UserRank `protobuf:"varint,3,opt,name=rank,proto3,enum=proto.UserRank" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68a7ca558839fd2b, []int{9}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetRank() UserRank {
	if m != nil {
		return m.Rank
	}
	return UserRank_regular
}

func init() {
	proto.RegisterEnum("proto.Site", Site_name, Site_value)
	proto.RegisterEnum("proto.UserRank", UserRank_name, UserRank_value)
	proto.RegisterType((*GetForeignUserRequest)(nil), "proto.GetForeignUserRequest")
	proto.RegisterType((*GetForeignUserResponse)(nil), "proto.GetForeignUserResponse")
	proto.RegisterType((*ValidateJWTRequest)(nil), "proto.validateJWTRequest")
	proto.RegisterType((*ValidateJWTResponse)(nil), "proto.validateJWTResponse")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*GetUserFromIDRequest)(nil), "proto.GetUserFromIDRequest")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
}

func init() { proto.RegisterFile("userservice.proto", fileDescriptor_68a7ca558839fd2b) }

var fileDescriptor_68a7ca558839fd2b = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4b, 0x6f, 0xda, 0x4c,
	0x14, 0xc5, 0xe6, 0x11, 0xb8, 0x3c, 0xe2, 0x6f, 0xc2, 0x47, 0xa9, 0xdb, 0x4a, 0xd4, 0x42, 0x55,
	0x94, 0x05, 0x8d, 0x48, 0xbb, 0xec, 0xa2, 0x2a, 0x22, 0xa2, 0xea, 0xca, 0x2d, 0xc9, 0xb2, 0x32,
	0xe1, 0x06, 0x4d, 0x0b, 0x1e, 0x3a, 0x33, 0x0e, 0xea, 0x7f, 0xed, 0xba, 0xbf, 0xa3, 0x9a, 0xf1,
	0x18, 0xdb, 0x98, 0x64, 0x81, 0xf0, 0x7d, 0xf8, 0xcc, 0x3d, 0xe7, 0xdc, 0x31, 0xfc, 0x17, 0x09,
	0xe4, 0x02, 0xf9, 0x03, 0xbd, 0xc3, 0xd1, 0x96, 0x33, 0xc9, 0x48, 0x55, 0xff, 0x79, 0x12, 0xfe,
	0xbf, 0x46, 0x39, 0x65, 0x1c, 0xe9, 0x2a, 0x9c, 0x0b, 0xe4, 0x3e, 0xfe, 0x8a, 0x50, 0x48, 0xf2,
	0x1e, 0x4e, 0x19, 0xa7, 0x2b, 0x1a, 0x06, 0xeb, 0x5b, 0x5c, 0x08, 0x2a, 0xb1, 0x6f, 0x0d, 0xac,
	0xf3, 0xce, 0xb8, 0x19, 0x03, 0x8c, 0x54, 0xca, 0x3f, 0xec, 0x21, 0x43, 0x68, 0xdf, 0xa7, 0x60,
	0xb3, 0x49, 0xdf, 0x1e, 0x58, 0xe7, 0x0d, 0x3f, 0x9f, 0xf4, 0x2e, 0xa1, 0x77, 0x78, 0xaa, 0xd8,
	0xb2, 0x50, 0x20, 0xe9, 0x41, 0x2d, 0xc4, 0xdd, 0x7c, 0x36, 0xd1, 0xa7, 0x95, 0x7d, 0x13, 0x79,
	0x6f, 0x80, 0x3c, 0x04, 0x6b, 0xba, 0x0c, 0x24, 0x7e, 0xbe, 0xfd, 0x96, 0x0c, 0xe9, 0x40, 0xf9,
	0xc7, 0x4e, 0xea, 0xd6, 0x86, 0xaf, 0x1e, 0xbd, 0x8f, 0x70, 0x96, 0xeb, 0x33, 0xb0, 0x7d, 0x38,
	0xa1, 0xe2, 0x46, 0x15, 0x74, 0x73, 0xdd, 0x4f, 0x42, 0x05, 0x11, 0xd1, 0xa5, 0x1e, 0xb3, 0xec,
	0xab, 0x47, 0xef, 0x8f, 0x05, 0xa7, 0x3e, 0xae, 0xa8, 0x90, 0xa9, 0x1a, 0x5d, 0xa8, 0xe2, 0x26,
	0xa0, 0x6b, 0x73, 0x54, 0x1c, 0x10, 0x17, 0xea, 0x4a, 0xd8, 0x30, 0xd8, 0xa0, 0xe1, 0xb9, 0x8f,
	0x55, 0x6d, 0x1b, 0x08, 0xb1, 0x63, 0x7c, 0xd9, 0x2f, 0xc7, 0xb5, 0x24, 0x26, 0x03, 0x68, 0x66,
	0xf4, 0xe8, 0x57, 0xf4, 0x44, 0xd9, 0x54, 0x51, 0xc6, 0xea, 0x11, 0x19, 0xc9, 0x15, 0x74, 0x4c,
	0x22, 0xb1, 0xa8, 0x56, 0xb4, 0xe8, 0xa0, 0xc5, 0x9b, 0x42, 0xeb, 0x0b, 0x5b, 0xd1, 0x30, 0xa1,
	0x96, 0x25, 0x61, 0x3d, 0x41, 0xc2, 0xce, 0x93, 0xf0, 0x5e, 0x43, 0xdb, 0xe0, 0x18, 0x8d, 0x8b,
	0x66, 0x0c, 0xc1, 0x49, 0x85, 0x7c, 0xb4, 0x6b, 0x04, 0xdd, 0x6b, 0x94, 0x8a, 0xd2, 0x94, 0xb3,
	0xcd, 0x6c, 0x92, 0x0c, 0xd6, 0x83, 0x5a, 0x14, 0x93, 0x37, 0xab, 0x10, 0x47, 0xde, 0x3d, 0xb4,
	0x72, 0x2b, 0xf3, 0x14, 0x81, 0xbd, 0x6f, 0x76, 0xd6, 0xb7, 0x21, 0x54, 0x78, 0x10, 0xfe, 0xd4,
	0xbe, 0x74, 0xc6, 0x8e, 0x51, 0x4b, 0xbd, 0xf4, 0x5d, 0xe5, 0x7d, 0x5d, 0xbd, 0x78, 0x0b, 0x15,
	0xbd, 0xd2, 0x2d, 0xa8, 0x87, 0xf4, 0x8e, 0xa9, 0x9f, 0x53, 0x52, 0xd1, 0x82, 0xae, 0xa9, 0xfa,
	0x39, 0x16, 0x69, 0xc2, 0xc9, 0x6f, 0x16, 0xc9, 0x68, 0x81, 0x8e, 0x7d, 0x71, 0x09, 0x8d, 0x3d,
	0x86, 0xaa, 0x70, 0x5c, 0x45, 0xeb, 0x80, 0x3b, 0x25, 0x15, 0x48, 0x1e, 0x09, 0x89, 0x4b, 0xc7,
	0x22, 0x0d, 0xa8, 0x06, 0xcb, 0x0d, 0x0d, 0x1d, 0x7b, 0xfc, 0xd7, 0x86, 0xa6, 0xe2, 0xf2, 0x35,
	0xbe, 0x9a, 0xe4, 0x03, 0xd4, 0x13, 0xc1, 0x48, 0xcf, 0x8c, 0x75, 0xb0, 0x8a, 0xee, 0xb3, 0x42,
	0x3e, 0xd6, 0xc1, 0x2b, 0x91, 0x77, 0x50, 0xd5, 0x96, 0x90, 0x33, 0xd3, 0x93, 0x35, 0xda, 0xed,
	0xe6, 0x93, 0xfb, 0xb7, 0xa6, 0xd0, 0xbc, 0x49, 0xaf, 0x0c, 0x79, 0x6e, 0xda, 0x8a, 0xd7, 0xcd,
	0x75, 0x8f, 0x95, 0xf6, 0x38, 0x9f, 0xa0, 0x9d, 0xf3, 0x91, 0xbc, 0x30, 0xed, 0xc7, 0xdc, 0x75,
	0x93, 0x11, 0xb3, 0x56, 0x7a, 0x25, 0x32, 0x4f, 0x97, 0x81, 0xf1, 0xe4, 0x03, 0x31, 0x9b, 0x90,
	0x97, 0x29, 0x56, 0xf1, 0x63, 0xe5, 0xbe, 0x7a, 0xa4, 0x9a, 0xc0, 0x2e, 0x6a, 0xba, 0x7e, 0xf5,
	0x2f, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x5f, 0xb9, 0xb0, 0x09, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ValidateJWT(ctx context.Context, in *ValidateJWTRequest, opts ...grpc.CallOption) (*ValidateJWTResponse, error)
	GetUserFromID(ctx context.Context, in *GetUserFromIDRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserForForeignUID(ctx context.Context, in *GetForeignUserRequest, opts ...grpc.CallOption) (*GetForeignUserResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateJWT(ctx context.Context, in *ValidateJWTRequest, opts ...grpc.CallOption) (*ValidateJWTResponse, error) {
	out := new(ValidateJWTResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/ValidateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserFromID(ctx context.Context, in *GetUserFromIDRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUserFromID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserForForeignUID(ctx context.Context, in *GetForeignUserRequest, opts ...grpc.CallOption) (*GetForeignUserResponse, error) {
	out := new(GetForeignUserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUserForForeignUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ValidateJWT(context.Context, *ValidateJWTRequest) (*ValidateJWTResponse, error)
	GetUserFromID(context.Context, *GetUserFromIDRequest) (*UserResponse, error)
	GetUserForForeignUID(context.Context, *GetForeignUserRequest) (*GetForeignUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) ValidateJWT(ctx context.Context, req *ValidateJWTRequest) (*ValidateJWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateJWT not implemented")
}
func (*UnimplementedUserServiceServer) GetUserFromID(ctx context.Context, req *GetUserFromIDRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFromID not implemented")
}
func (*UnimplementedUserServiceServer) GetUserForForeignUID(ctx context.Context, req *GetForeignUserRequest) (*GetForeignUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserForForeignUID not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/ValidateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateJWT(ctx, req.(*ValidateJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserFromID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFromIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserFromID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUserFromID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserFromID(ctx, req.(*GetUserFromIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserForForeignUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForeignUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserForForeignUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUserForForeignUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserForForeignUID(ctx, req.(*GetForeignUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "ValidateJWT",
			Handler:    _UserService_ValidateJWT_Handler,
		},
		{
			MethodName: "GetUserFromID",
			Handler:    _UserService_GetUserFromID_Handler,
		},
		{
			MethodName: "GetUserForForeignUID",
			Handler:    _UserService_GetUserForForeignUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userservice.proto",
}
