ARG UBUNTU_IMAGE

FROM ${UBUNTU_IMAGE}

# install minio binaries
RUN apt --assume-yes update && \
  apt --assume-yes install wget && \
  wget https://dl.min.io/server/minio/release/linux-amd64/minio -O /usr/local/bin/minio && \
  chmod +x /usr/local/bin/minio && \
  wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && \
  chmod +x /usr/local/bin/mc

COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
