# NOTE: because migrations come from outside the `postgres` directory,
#       we build this image from project root, symlinking this file to
#       Dockerfile.postgres
ARG POSTGRES_IMAGE


FROM ${POSTGRES_IMAGE}

ARG FLYWAY_VERSION

RUN apt --assume-yes update && \
  apt --assume-yes install wget && \
  wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/${FLYWAY_VERSION}/flyway-commandline-${FLYWAY_VERSION}-linux-x64.tar.gz | tar xvz \
  && ln --symbolic `pwd`/flyway-${FLYWAY_VERSION}/flyway /usr/local/bin \
  && chmod a+x /usr/local/bin/flyway

USER postgres
COPY --chown=postgres:postgres postgres/ /postgres/

# add migrations from services
COPY --chown=postgres:postgres user_service/migrations/ /postgres/user_service/migrations/
COPY --chown=postgres:postgres scheduler/migrations/ /postgres/scheduler/migrations/
COPY --chown=postgres:postgres video_service/migrations/ /postgres/video_service/migrations/

ENTRYPOINT ["/postgres/entrypoint.sh"]
